# Generated by Django 4.1.6 on 2023-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospitaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitaldata_name', models.CharField(max_length=100, verbose_name='hospital_name')),
                ('hospitaldata_contact', models.IntegerField(max_length=12, verbose_name='hospital_contact')),
                ('hospitaldata_address', models.TextField(verbose_name='hospital_address')),
                ('hospitaldata_email', models.EmailField(max_length=254)),
                ('hospitaldata_specilazation', models.CharField(max_length=200, verbose_name='hospital_specialization')),
            ],
        ),
    ]
